### ISSUE TITLE
截图占用了大量空间，克隆仓库会很慢

### ISSUE THREAD

**Issue by aimerneige** [loaden/nspawn-deepinwine#4]
如题，可以考虑将截图文件另行处理

![image](https://user-images.githubusercontent.com/51701792/146931614-a03fd63f-6d1b-4999-b08f-62141ff04b34.png)

**Comment by loaden** [comment]
才21MB啊，截图是想让更多人看见效果图。

**Comment by aimerneige** [comment]
> 才21MB啊

虽然图片只有 21 MB，但是算上 git 的缓存的话一共有 60 MB 了。

> 想让更多人看见效果图

截图并不一定要放在当前 github 仓库里，可以放在图床或者其他仓库里，本项目直接在 README 里贴链接就可以了。

本项目的一些脚本并不能独立运行（source 指令），如果要使用，最方便的还是 clone 一份仓库，但是本来就是几个很小的脚本，却要花很长时间 clone 仓库里面的图片，既费流量又费时间。

**Comment by loaden** [comment]
我前几天尝试本地截图都删除了，本地的git库减小到400K左右了，但是我没办法让gitee和github的远程仓库减肥。

**Comment by aimerneige** [comment]
有空我来写一个教程之类的给你。

**Comment by loaden** [comment]
本地我已经完成了，刚才又尝试了一下，发现远程仓库这样执行就可以了：

> git push --tags  --force --prune
> git push --all --force --prune

**Comment by loaden** [comment]
没问题的话，这个issue关了？

**Comment by aimerneige** [comment]
好的👌
