### ISSUE TITLE
你是之前的CB的开发者loaden么？打个招呼！

### ISSUE THREAD

**Issue by asmwarrior** [loaden/nspawn-deepinwine#7]
最近CB在搞LSP，见：

Code completion using LSP and clangd — https://forums.codeblocks.org/index.php/topic,24357.0.html

**Comment by loaden** [comment]
惊喜！很高兴CB加入了Clang代码完成功能。好久不见，还在给CB开发吗？我gmail基本上没办法访问了，因为懒得弄梯子。现在只玩Linux发行版，很少编程了，哈哈，头疼，年纪大了。很怀念当初CB开发的美好时光。

**Comment by asmwarrior** [comment]
> 惊喜！很高兴CB加入了Clang代码完成功能。好久不见，还在给CB开发吗？
对，我还在给CB修修补补。不过没以前多了。


> 我gmail基本上没办法访问了，因为懒得弄梯子。现在只玩Linux发行版，很少编程了，哈哈，头疼，年纪大了。很怀念当初CB开发的美好时光。
我看你怎么在玩Linux下面的Windows软件支持了？

你现在常用的联系方法是？QQ？国内邮箱？现在还经常在csdn么？还是主要是github了？

**Comment by loaden** [comment]
QQ最近也没用了，我QQ号 5003160，邮件就用的QQ邮箱。github偶尔上来看看，因为github老被墙，经常打不开。

**Comment by asmwarrior** [comment]
好的，我以后有事情就qq邮件联系你吧。
github你还是需要弄一个什么爬墙的工具，确实经常会被墙掉。
这个issue我给他关闭掉了。
